Merge upstream
SkynetLabs/tus-js-client pull request #27
Opened 2022-08-21 19:00 UTC by m-cat

# PULL REQUEST

## Overview

Merge in upstream changes. This includes v3.0 changes which should make parallel uploads work with Node. See https://github.com/SkynetLabs/nodejs-skynet/pull/195#issuecomment-1221600861.

2022-08-21 19:01 UTC, m-cat commented
@kwypchlo

2022-08-22 09:42 UTC, kwypchlo approved these changes

2022-08-24 12:33 UTC, MSevey requested changes
Build is failing.

2022-08-25 07:05 UTC, m-cat commented
@MSevey Looks like an issue with browserstack secrets. I think I sent you mine once, are they still set in the repo? Or can paste some secrets from your browserstack account or just ignore the failed run.

2022-08-29 20:06 UTC, merged